#!/bin/sh /etc/rc.common

START=100
STOP=150

EXTRA_COMMANDS="enable_firewall"
EXTRA_HELP="        enable_firewall  Enable firewall redirects"

start() {
	/usr/bin/node /www/ecr-app/index.js > /dev/null &
	#/usr/bin/node /www/ecr-app/hid.js > /dev/null &
	logger "We run nodejs and firewall"
}

boot() {
	start
}

stop() {
	echo stop
	# commands to kill application
}

enable_firewall() {
	/sbin/uci set firewall.@zone[1].forward='ACCEPT'
	/sbin/uci delete firewall.@zone[1].network
	/sbin/uci add_list firewall.@zone[1].network='wwan'
	/sbin/uci add_list firewall.@zone[1].network='wan'
	/sbin/uci add_list firewall.@zone[1].network='usb1'
	/sbin/uci add_list firewall.@zone[1].network='bnep0'
	/sbin/uci delete firewall.@zone[0].network
	/sbin/uci add_list firewall.@zone[0].network='wlan'
	/sbin/uci add_list firewall.@zone[0].network='usb0'
	/sbin/uci commit
	
	/sbin/uci add firewall rule
	/sbin/uci set firewall.@rule[-1].name='Allow-localtunnel'
	/sbin/uci set firewall.@rule[-1].dest_port='1191'
	/sbin/uci set firewall.@rule[-1].src_port='1191'
	/sbin/uci set firewall.@rule[-1].proto='tcp'
	/sbin/uci set firewall.@rule[-1].target='ACCEPT'
	/sbin/uci commit firewall
	
	/etc/init.d/firewall restart
}